-- TO CHANGE NOT NULL
-- USE SET
ALTER TABLE world
ALTER COLUMN population SET NOT NULL;
-- column population set to NOT NULL

-- HOW TO CHANGE BACK NOT NULL -> NULL
-- USE DROP
ALTER TABLE world
ALTER COLUMN population DROP NOT NULL;
-- column population set to NULL

-- HOW TO CHANGE COLUMN NAME
-- USE RENAME
ALTER TABLE world
RENAME COLUMN population TO region;
-- column population is change to region

-- HOW TO CHANGE COLUMN DATA TYPE
-- USE TYPE
ALTER TABLE world
ALTER COLUMN population TYPE INT;

-- CARA UBAH VALUES DALAM COLUMN
-- GUNA UPDATE, SET DAN WHERE
UPDATE world
SET benua = 'ASIA BARAT'
WHERE name = 'MESIR';
-- 1. UPDATE TABLE_NAME
-- 2. SET KAN COLUMN_NAME = 'VALUES'
-- 3. WHERE/DIMANA COLUMN_NAME = 'VALUES';
UPDATE world
SET name = 'SOUTH KOREA'
WHERE name = 'KOREA SELATAN';
-- MAKSUDNYA SETKAN COLOUMN BENUA KEPADA ASIA BARAT, DIMANA NAMA IALAH MESIR



